### PR TITLE
update module readme title to adapter

### PR DESCRIPTION
**Pull request by DariushMoh**
Related to https://code.inmanta.com/solutions/tickets/-/issues/126

### CODE REVIEW

**Review by bartv — APPROVED** [review]

**Review by bartv — CHANGES_REQUESTED** [review]
Not sure that this is useful

**Comment by bartv** [comment]
The problem is that some are modules. So I don't think we should change the template

**Comment by DariushMoh** [comment]
Okay I will just close the pr

**Comment by DariushMoh** [comment]
Okay I will just close the pr

**Pull request closed without merging**
